"""add paystack_subaccount to product

Revision ID: 84400878347d
Revises: 001
Create Date: 2026-09-07 20:54:42.745849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84400878347d'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('products', sa.Column('paystack_subaccount', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'paystack_subaccount')
    op.alter_column('admin_users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
